---
  - file: path=/etc/default/tomcat8 owner=root group=root mode=0644
  - lineinfile: dest=/etc/default/tomcat8 line="# GUACAMOLE EVN VARIABLE"
  - lineinfile: dest=/etc/default/tomcat8 line="GUACAMOLE_HOME=/etc/guacamole"

  - name: Download Guacamole Files
    get_url:
      url: http://downloads.sourceforge.net/project/guacamole/current/binary/guacamole-0.9.9.war
      dest: /tmp/guacamole-0.9.9.war
    get_url:
      url: http://sourceforge.net/projects/guacamole/files/current/source/guacamole-server-0.9.9.tar.gz
      dest: /tmp/guacamole-server-0.9.9.tar.gz
    get_url:
      url: http://sourceforge.net/projects/guacamole/files/current/extensions/guacamole-auth-jdbc-0.9.9.tar.gz
      dest: /tmp/guacamole-auth-jdbc-0.9.9.tar.gz
    get_url:
      url: http://dev.mysql.com/get/Downloads/Connector/j/mysql-connector-java-5.1.39.tar.gz
      dest: mysql-connector-java-5.1.39.tar.gz

  - name: Extract Guacamole Files
    unarchive: src=/tmp/guacamole-server-0.9.9.tar.gz dest=/tmp/guacamole-server-0.9.9
    unarchive: src=/tmp/guacamole-auth-jdbc-0.9.9.tar.gz dest=/tmp/guacamole-auth-jdbc-0.9.9
    unarchive: src=/tmp/mysql-connector-java-5.1.39.tar.gz dest=/tmp/mysql-connector-java-5.1.39

  - name: Make Directorys
    file: path=/etc/guacamole state=directory
    file: mkdir /etc/guacamole/lib state=directory
    file: mkdir /etc/guacamole/extensions state=directory


# # Install GUACD
# cd guacamole-server-0.9.9
# ./configure --with-init-dir=/etc/init.d
# make
# make install
# ldconfig
# systemctl enable guacd
# cd ..
#
#
# # Move files to correct locations
# mv guacamole-0.9.9.war /etc/guacamole/guacamole.war
# ln -s /etc/guacamole/guacamole.war /var/lib/tomcat8/webapps/
# ln -s /usr/local/lib/freerdp/* /usr/lib/x86_64-linux-gnu/freerdp/.
# cp mysql-connector-java-5.1.39/mysql-connector-java-5.1.39-bin.jar /etc/guacamole/lib/
# cp guacamole-auth-jdbc-0.9.9/mysql/guacamole-auth-jdbc-mysql-0.9.9.jar /etc/guacamole/extensions/
#
#
#
#
#
#
# rm -rf /usr/share/tomcat8/.guacamole
# ln -s /etc/guacamole /usr/share/tomcat8/.guacamole
