---
- hosts: guac
  become: true
  tasks:
  - name: Update Cache
    apt: update_cache=yes
  - name: Install Deps
    apt: name=libpng12-dev
    apt: name=libossp-uuid-dev
    apt: name=libfreerdp-dev
    apt: name=libpango1.0-dev
    apt: name=libssh2-1-dev
    apt: name=libtelnet-dev
    apt: name=libvncserver-dev
    apt: name=libpulse-dev
    apt: name=libssl-dev
    apt: name=libvorbis-dev
    apt: name=libwebp-dev
    apt: name=mysql-server
    apt: name=mysql-client
    apt: name=mysql-common
    apt: name=mysql-utilities
    apt: name=tomcat8
    apt: name=freerdp
    apt: name=ghostscript
    apt: name=wget
    apt: name=curl

  - name: Download and install libjpeg-turbo
    get_url:
      url: http://downloads.sourceforge.net/project/libjpeg-turbo/1.5.0/libjpeg-turbo-official_1.5.0_amd64.deb
      dest: /tmp/libjpeg-turbo-official_1.5.0_amd64.deb
    command: dpkg -i /tmp/libjpeg-turbo-official_1.5.0_amd64.deb

  - file: path=/etc/default/tomcat8 owner=root group=root mode=0644
  - lineinfile: dest=/etc/default/tomcat8 line="# GUACAMOLE EVN VARIABLE"
  - lineinfile: dest=/etc/default/tomcat8 line="GUACAMOLE_HOME=/etc/guacamole"

  - name: Download Guacample Files
  - command: wget -O guacamole-0.9.9.war http://downloads.sourceforge.net/project/guacamole/current/binary/guacamole-0.9.9.war
  - command: wget -O guacamole-server-0.9.9.tar.gz http://sourceforge.net/projects/guacamole/files/current/source/guacamole-server-0.9.9.tar.gz
  - command: wget -O guacamole-auth-jdbc-0.9.9.tar.gz http://sourceforge.net/projects/guacamole/files/current/extensions/guacamole-auth-jdbc-0.9.9.tar.gz
  - command: wget -O mysql-connector-java-5.1.39.tar.gz http://dev.mysql.com/get/Downloads/Connector/j/mysql-connector-java-5.1.39.tar.gz

  - name: Extract Guacamole Files
  - command: tar -xzf guacamole-server-0.9.9.tar.gz
  - command: tar -xzf guacamole-auth-jdbc-0.9.9.tar.gz
  - command: tar -xzf mysql-connector-java-5.1.39.tar.gz

  - file: path=/etc/ state=directory

  - name: MAKE DIRECTORIES
  - file: path=/etc/guacamole state=directory
  - file: mkdir /etc/guacamole/lib state=directory
  - file: mkdir /etc/guacamole/extensions state=directory




  - name: ensure services are running
    service:
      name: tomcat8
      state: started



----left to configure

# Install GUACD
cd guacamole-server-0.9.9
./configure --with-init-dir=/etc/init.d
make
make install
ldconfig
systemctl enable guacd
cd ..

# Move files to correct locations
mv guacamole-0.9.9.war /etc/guacamole/guacamole.war
ln -s /etc/guacamole/guacamole.war /var/lib/tomcat8/webapps/
ln -s /usr/local/lib/freerdp/* /usr/lib/x86_64-linux-gnu/freerdp/.
cp mysql-connector-java-5.1.39/mysql-connector-java-5.1.39-bin.jar /etc/guacamole/lib/
cp guacamole-auth-jdbc-0.9.9/mysql/guacamole-auth-jdbc-mysql-0.9.9.jar /etc/guacamole/extensions/

# Configure guacamole.properties
echo "mysql-hostname: localhost" >> /etc/guacamole/guacamole.properties
echo "mysql-port: 3306" >> /etc/guacamole/guacamole.properties
echo "mysql-database: guacamole_db" >> /etc/guacamole/guacamole.properties
echo "mysql-username: guacamole_user" >> /etc/guacamole/guacamole.properties
echo "mysql-password: $guacdbuserpassword" >> /etc/guacamole/guacamole.properties
rm -rf /usr/share/tomcat8/.guacamole
ln -s /etc/guacamole /usr/share/tomcat8/.guacamole

# restart tomcat
service tomcat8 restart

# Create guacamole_db and grant guacamole_user permissions to it
echo "create database guacamole_db; create user 'guacamole_user'@'localhost' identified by \"$guacdbuserpassword\";GRANT SELECT,INSERT,UPDATE,DELETE ON guacamole_db.* TO 'guacamole_user'@'localhost';flush privileges;" | mysql -u root -p$mysqlrootpassword

cat guacamole-auth-jdbc-0.9.9/mysql/schema/*.sql | mysql -u root -p$mysqlrootpassword guacamole_db

rm libjpeg-turbo-official_1.5.0_amd64.deb
rm guacamole-server-0.9.9.tar.gz
rm guacamole-auth-jdbc-0.9.9.tar.gz
rm mysql-connector-java-5.1.39.tar.gz

rm -rf mysql-connector-java-5.1.39/
rm -rf guacamole-auth-jdbc-0.9.9/
rm -rf guacamole-server-0.9.9/
