---
- name: Install Deps
  apt: name={{item}}
  with_items:
      - libpng12-dev
      - libossp-uuid-dev
      - libfreerdp-dev
      - libpango1.0-dev
      - libssh2-1-dev
      - libtelnet-dev
      - libvncserver-dev
      - libpulse-dev
      - libssl-dev
      - libvorbis-dev
      - libwebp-dev
      - freerdp
      - ghostscript
      - wget
      - curl

- name: Download and install libjpeg-turbo
  get_url:
  url: http://downloads.sourceforge.net/project/libjpeg-turbo/1.5.0/libjpeg-turbo-official_1.5.0_amd64.deb
  dest: /tmp/libjpeg-turbo-official_1.5.0_amd64.deb
  command: dpkg -i /tmp/libjpeg-turbo-official_1.5.0_amd64.deb
